<div class="page-header">
	<h1>Listado de Departamentos</h1>
</div>

<div class="row">
	<div class="col-xs-12">
		<div class="table-header-borde">&nbsp;</div>
		<div>
			<table id="dynamic-table"
				class="table table-striped table-bordered table-hover">
				<thead>
					<tr>
						<th class="opciones-grid col-xs-3 col-lg-1"><a
							href="<?php echo $this->url('recursos', array('controller' => 'departamentos', 'action'=>'ingresar'));?>"
							class="btn btn-sm btn-primary"> <i class="fa fa-plus-circle"></i>
								<span class="hidden-xs">Nuevo</span>
						</a></th>
						<th>Departamento</th>
					</tr>
				</thead>

				<tbody>
					<?php
    foreach ($this->departamentos as $cargos) :
        ?>
                 <tr>
						<td class="iconos-ejecucion-grid"><a class="fa-lg"
							href="<?php echo $this->url('recursos', array('controller' => 'departamentos', 'action' => 'editar', 'id' => $cargos->getDep_id()))?>"><i
								class="fa fa-pencil"></i></a>&nbsp;&nbsp;&nbsp; <a class="fa-lg"
							href="<?php echo $this->url('recursos', array('controller' => 'departamentos', 'action' => 'eliminar', 'id' => $cargos->getDep_id()))?>"
							onclick="return eliminarRegistro('<?php echo $cargos->getDep_descripcion()?>');"><i
								class="fa fa-trash-o"></i></a></td>
						<td><?php echo $this->escapeHtml($cargos->getDep_descripcion());?></td>
					</tr>
                 <?php endforeach; ?>

				</tbody>
			</table>
		</div>
	</div>
</div>