<h3 
	style="	min-height:200px;
			font-weight: 700; 
			margin:0 auto; 
			width:500px; 
			text-align:center;
			<?php if(!$this->estaLogeado): ?>
				color: white; 
				margin-top:300px;
			<?php else: ?>
				color: #5C9CCC; 
				margin-top:200px;
			<?php endif; ?> 
			"
		>
	<?php echo $this->mensaje ?>
<p style='font-size:16px; font-weight:normal'>Solicite permisos con el administrador del sistema</p>
<?php if(!$this->estaLogeado): ?>
<a style="font-size:20px" href="<?php echo $this->url('application',array('controller'=>'login')); ?>">Ingresar al Sistema</a>
<?php endif; ?>
</h3>