<div class="footer">
	<div class="footer-inner">
		<!-- #section:basics/footer -->
		<div class="footer-content">
			<span class="bigger-120">
						&copy; <?php echo date('Y'); echo ' ' . $this->translate('All rights reserved.')?>
					</span> &nbsp; &nbsp; <span class="action-buttons hidden-xs"> <a href="#"> <i
					class="ace-icon fa fa-twitter-square light-blue bigger-150"></i>
			</a> <a href="#"> <i
					class="ace-icon fa fa-facebook-square text-primary bigger-150"></i>
			</a> <a href="#"> <i
					class="ace-icon fa fa-rss-square orange bigger-150"></i>
			</a>
			</span>
		</div>

		<!-- /section:basics/footer -->
	</div>
</div>