<!-- #section:basics/sidebar -->
<div id="sidebar" class="sidebar responsive sidebar-fixed">
	<?php echo $this->partial('partial/modulos')?>

	<ul class="nav nav-list">
		<li class="active"><a href="<?php echo $this->url('recursos', array('controller' => 'index'))?>"> <i
				class="menu-icon fa fa-tachometer"></i> <span class="menu-text">
					Inicio </span>
		</a> <b class="arrow"></b></li>
		
		<li><a href="<?php echo $this->url('recursos', array('controller' => 'departamentos', 'action' => 'listado'))?>"> <i
				class="menu-icon fa fa-tachometer"></i> <span class="menu-text">
					Departamentos </span>
		</a> <b class="arrow"></b></li>

		<li class=""><a href="<?php echo $this->url('recursos', array('controller' => 'cargos', 'action' => 'listado'))?>"> <i
				class="menu-icon fa fa-desktop"></i> <span class="menu-text"> Cargos </span>
		</a> <b class="arrow"></b>
	   </li>
	   
	   <li class=""><a href="<?php echo $this->url('recursos', array('controller' => 'competencias', 'action' => 'listado'))?>"> <i
				class="menu-icon fa fa-desktop"></i> <span class="menu-text"> Competencias </span>
		</a> <b class="arrow"></b>
	   </li>

		<li class=""><a href="<?php echo $this->url('recursos', array('controller' => 'personal', 'action' => 'listado'))?>"> <i
				class="menu-icon fa fa-pencil-square-o"></i> <span class="menu-text">
					Empleados </span>
		</a> <b class="arrow"></b></li>

		<li class=""><a href="<?php echo $this->url('recursos', array('controller' => 'experiencia', 'action' => 'listado'))?>"> <i
				class="menu-icon fa fa-list-alt"></i> <span class="menu-text">
					Experiencia </span>
		</a> <b class="arrow"></b></li>

		<li class=""><a href="#" class="dropdown-toggle"> <i
				class="menu-icon fa fa-tag"></i> <span class="menu-text"> Evaluaciones
			</span> <b class="arrow fa fa-angle-down"></b>
		</a> <b class="arrow"></b>
		
		<ul class="submenu">
		        <li class=""><a href="<?php echo $this->url('recursos', array('controller' => 'evaluaciones', 'action' => 'listado'))?>"> <i
						class="menu-icon fa fa-caret-right"></i> Evaluaciones
				</a> <b class="arrow"></b></li>
				
				<li class=""><a href="<?php echo $this->url('recursos', array('controller' => 'desempeno', 'action' => 'listado'))?>"> <i
						class="menu-icon fa fa-caret-right"></i> Desempe&ntilde;o
				</a> <b class="arrow"></b></li>
			</ul>
		</li>
		
		<li class=""><a href="<?php echo $this->url('recursos', array('controller' => 'idiomas', 'action' => 'listado'))?>"> <i
				class="menu-icon fa fa-list-alt"></i> <span class="menu-text">
					Idiomas </span>
		</a> <b class="arrow"></b></li>

		<li class=""><a href="<?php echo $this->url('recursos', array('controller' => 'grados', 'action' => 'listado'))?>"> <i
				class="menu-icon fa fa-file-o"></i> <span class="menu-text"> Grados  
			</span> 
		</a> <b class="arrow"></b>
</li>
	</ul>
	<!-- /.nav-list -->

	<!-- #section:basics/sidebar.layout.minimize -->
	<div class="sidebar-toggle sidebar-collapse" id="sidebar-collapse">
		<i class="ace-icon fa fa-angle-double-left"
			data-icon1="ace-icon fa fa-angle-double-left"
			data-icon2="ace-icon fa fa-angle-double-right"></i>
	</div>

	<!-- /section:basics/sidebar.layout.minimize -->
	<script type="text/javascript">
					try{ace.settings.check('sidebar' , 'collapsed')}catch(e){}
				</script>
</div>