<!-- #section:basics/sidebar -->
<div id="sidebar" class="sidebar responsive sidebar-fixed">
	<?php echo $this->partial('partial/modulos')?>

	<ul class="nav nav-list">
		<li class="active"><a href="<?php echo $this->url('mejoras', array('controller' => 'index'))?>"> <i
				class="menu-icon fa fa-tachometer"></i> <span class="menu-text">
					Inicio </span>
		</a> <b class="arrow"></b></li>

		<li class=""><a href="#" class="dropdown-toggle"> <i
				class="menu-icon fa fa-desktop"></i> <span class="menu-text">
					Acciones </span> <b class="arrow fa fa-angle-down"></b>
		</a> <b class="arrow"></b>

			<ul class="submenu">

				<li class=""><a href="<?php echo $this->url('mejoras', array('controller' => 'acciones', 'action' => 'listado'))?>"> <i
						class="menu-icon fa fa-caret-right"></i> Acciones
				</a> <b class="arrow"></b></li>

				<li class=""><a href="<?php echo $this->url('mejoras', array('controller' => 'tipoaccion', 'action' => 'listado'))?>"> <i
						class="menu-icon fa fa-caret-right"></i> Tipo de Acci&oacute;n
				</a> <b class="arrow"></b></li>

				<li class=""><a href="<?php echo $this->url('mejoras', array('controller' => 'tipohallazgo', 'action' => 'listado'))?>"> <i
						class="menu-icon fa fa-caret-right"></i> Tipo Hallazgo
				</a> <b class="arrow"></b></li>

				<li class=""><a href="<?php echo $this->url('mejoras', array('controller' => 'estadoaccion', 'action' => 'listado'))?>"> <i
						class="menu-icon fa fa-caret-right"></i> Estado Acci&oacute;n
				</a> <b class="arrow"></b></li>

				<li class=""><a href="<?php echo $this->url('mejoras', array('controller' => 'accionevaluacion', 'action' => 'listado'))?>"> <i
						class="menu-icon fa fa-caret-right"></i> Acci&oacute;n
						Evaluaci&oacute;n
				</a> <b class="arrow"></b></li>

				<li class=""><a href="<?php echo $this->url('mejoras', array('controller' => 'motivos', 'action' => 'listado'))?>"> <i
						class="menu-icon fa fa-caret-right"></i> Motivos
				</a> <b class="arrow"></b></li>
			</ul></li>
	</ul>
	<!-- /.nav-list -->

	<!-- #section:basics/sidebar.layout.minimize -->
	<div class="sidebar-toggle sidebar-collapse" id="sidebar-collapse">
		<i class="ace-icon fa fa-angle-double-left"
			data-icon1="ace-icon fa fa-angle-double-left"
			data-icon2="ace-icon fa fa-angle-double-right"></i>
	</div>

	<!-- /section:basics/sidebar.layout.minimize -->
	<script type="text/javascript">
					try{ace.settings.check('sidebar' , 'collapsed')}catch(e){}
				</script>
</div>