<!-- #section:basics/sidebar -->
<div id="sidebar" class="sidebar responsive sidebar-fixed">
	<?php echo $this->partial('partial/modulos')?>

	<ul class="nav nav-list">
		<li class="active"><a href="<?php echo $this->url('usuarios', array('controller' => 'index'))?>"> <i
				class="menu-icon fa fa-tachometer"></i> <span class="menu-text">
					Inicio </span>
		</a> <b class="arrow"></b></li>

		<li class=""><a href="<?php echo $this->url('usuarios', array('controller' => 'modulos', 'action' => 'listado'))?>"> <i
				class="menu-icon fa fa-tachometer"></i> <span class="menu-text">
					M&oacute;dulos </span>
		</a> <b class="arrow"></b></li>

		<li class=""><a href="<?php echo $this->url('usuarios', array('controller' => 'roles', 'action' => 'listado'))?>"> <i
				class="menu-icon fa fa-tachometer"></i> <span class="menu-text">
					Roles </span>
		</a> <b class="arrow"></b></li>

		<li class=""><a href="<?php echo $this->url('usuarios', array('controller' => 'usuarios', 'action' => 'listado'))?>"> <i
				class="menu-icon fa fa-tachometer"></i> <span class="menu-text">
					Usuarios </span>
		</a> <b class="arrow"></b></li>

		<li class=""><a href="<?php echo $this->url('usuarios', array('controller' => 'aplicaciones', 'action' => 'listado'))?>"> <i
				class="menu-icon fa fa-desktop"></i> <span class="menu-text"> Aplicaciones
			</span>
		</a> <b class="arrow"></b></li>

	</ul>
	<!-- /.nav-list -->

	<!-- #section:basics/sidebar.layout.minimize -->
	<div class="sidebar-toggle sidebar-collapse" id="sidebar-collapse">
		<i class="ace-icon fa fa-angle-double-left"
			data-icon1="ace-icon fa fa-angle-double-left"
			data-icon2="ace-icon fa fa-angle-double-right"></i>
	</div>

	<!-- /section:basics/sidebar.layout.minimize -->
	<script type="text/javascript">
					try{ace.settings.check('sidebar' , 'collapsed')}catch(e){}
				</script>
</div>