<div class="sidebar-shortcuts" id="sidebar-shortcuts">
	<div class="sidebar-shortcuts-large" id="sidebar-shortcuts-large">
		<a
			href="<?php echo $this->url('auditorias', array('controller' => 'index', 'action' => 'index'))?>"
			class="btn btn-danger"> <i class="ace-icon fa fa-signal" title="Auditor&iacute;a"></i>
		</a> <a
			href="<?php echo $this->url('mejoras', array('controller' => 'index', 'action' => 'index'))?>"
			class="btn btn-info"> <i class="ace-icon fa fa-pencil" title="Mejoras"></i>
		</a>

		<!-- #section:basics/sidebar.layout.shortcuts -->
		<a
			href="<?php echo $this->url('procesos', array('controller' => 'index', 'action' => 'index'))?>"
			class="btn btn-warning"> <i class="ace-icon fa fa-users" title="Procesos"></i>
		</a> 
		<a
			href="<?php echo $this->url('recursos', array('controller' => 'index', 'action' => 'index'))?>"
			class="btn btn-success"> <i class="ace-icon fa fa-cogs" title="Recursos"></i>
		</a>

		<!-- /section:basics/sidebar.layout.shortcuts -->
	</div>

	<div class="sidebar-shortcuts-mini" id="sidebar-shortcuts-mini">
		<span class="btn btn-success"></span> <span class="btn btn-info"></span>

		<span class="btn btn-warning"></span> <span class="btn btn-danger"></span>
	</div>
</div>
<!-- /.sidebar-shortcuts -->