<div class="breadcrumbs breadcrumbs-fixed" id="breadcrumbs">
	<!-- #section:basics/content.breadcrumbs -->
	<ul class="breadcrumb">
		
		<?php
$contNav = 0;

foreach ($this->ruta as $rowNav => $valNav) {
    if ($contNav == 0) {
        echo '<li><i class="ace-icon fa fa-home home-icon"></i> ' . $valNav . '</li>';
    } else {
        echo '<li class="active">' . $valNav . '</li>';
    }
    
    $contNav ++;
}

$contNav = 0;
?>
	</ul>
	<!-- /.breadcrumb -->
</div>


