<style>
/* some elements used in demo only */
.dropdown-preview {
	margin: 0 10px;
	display: inline-block;
}

.dropdown-preview>.dropdown-menu {
	display: block;
	position: static;
	box-shadow: 0 0px 0px !important;
}

.tipo-back:hover {
	background-color: red !important;
}
</style>
<div class="page-header">
	<h1>Listado de Cargos</h1>
</div>

<div class="row">
	<div class="col-xs-12">
		<div class="table-header-borde">&nbsp;</div>
		<div>
			<table id="dynamic-table"
				class="table table-striped table-bordered table-hover">
				<thead>
					<tr>
						<th class="opciones-grid col-xs-3 col-lg-1"><a
							href="<?php echo $this->url('recursos', array('controller' => 'cargos', 'action'=>'ingresar'));?>"
							class="btn btn-sm btn-primary"> <i class="fa fa-plus-circle"></i>
								<span class="hidden-xs">Nuevo</span>
						</a></th>
						<th>Departamento</th>
						<th>Cargo</th>
						<th>Misi&oacute;n</th>
						<th>Conocimiento</th>
					</tr>
				</thead>

				<tbody>
					<?php
    foreach ($this->cargos as $competencias) :
        ?>
                 <tr>
						<td class="iconos-ejecucion-grid"><a class="fa-lg"
							href="<?php echo $this->url('recursos', array('controller' => 'cargos', 'action' => 'editar', 'id' => $competencias->getCar_id()))?>"><i
								class="fa fa-pencil"></i></a>&nbsp;&nbsp;&nbsp; <a class="fa-lg"
							href="<?php echo $this->url('recursos', array('controller' => 'cargos', 'action' => 'eliminar', 'id' => $competencias->getCar_id()))?>"
							onclick="return eliminarRegistro('<?php echo $competencias->getCar_descripcion()?>');"><i
								class="fa fa-trash-o"></i></a> <span class="dropdown-preview"
							style="float: right; margin-left: 0px; padding-left: 0px;">
								<ul class="dropdown-menu"
									style="margin: 0 0; padding: 0 0; min-width: 0px; border: 0px solid; background: transparent;">
									<li class="dropup dropdown-hover"><span href="#" tabindex="-1"
										class="clearfix"
										style="margin: 0 0; padding: 0 0; background: transparent;"> <span
											class="pull-left"><i class="ace-icon fa fa-cog fa-lg"></i></span>
									</span>
										<ul class="dropdown-menu pull-left"
											style="width: 270px; padding-left: 0px;">
											<li class="text-center"><span style="padding-right: 5px;"><a
													href=""><i class='fa fa-lg fa-trash-o'></i></a></span> <span
												style="padding-right: 5px;"><a href=""><i
														class='fa fa-lg fa-trash-o'></i></a></span> <span
												style="padding-right: 5px;"><a href=""><i
														class='fa fa-lg fa-trash-o'></i></a></span> <span
												style="padding-right: 5px;"><a href=""><i
														class='fa fa-lg fa-trash-o'></i></a></span> <span
												style="padding-right: 5px;"><a href=""><i
														class='fa fa-lg fa-trash-o'></i></a></span> <span
												style="padding-right: 5px;"><a href=""><i
														class='fa fa-lg fa-trash-o'></i></a></span> <span
												style="padding-right: 5px;"><a href=""><i
														class='fa fa-lg fa-trash-o'></i></a></span> <span
												style="padding-right: 5px;"><a href=""><i
														class='fa fa-lg fa-trash-o'></i></a></span> <span
												style="padding-right: 5px;"><a href=""><i
														class='fa fa-lg fa-trash-o'></i></a></span> <span style=""><a
													href=""><i class='fa fa-lg fa-trash-o'></i></a></span></li>
										</ul></li>
								</ul>
						</span></td>
						<td><?php echo $this->escapeHtml($competencias->getDep_id());?></td>
						<td><?php echo $this->escapeHtml($competencias->getCar_descripcion());?></td>
						<td><?php echo $this->escapeHtml($competencias->getCar_mision());?></td>
						<td><?php echo $this->escapeHtml($competencias->getCar_conocimiento());?></td>
					</tr>
                 <?php endforeach; ?>

				</tbody>
			</table>
		</div>
	</div>
</div>
